name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
          yarn install
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
